---
- name: include os specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: install epel repo
  yum:
    name: "{{ item.url }}"
    state: present
  with_items:
    - url: "{{ epel_repo }}"

- include: install.yml

- include: configure.yml
